import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Shared source-tracking fields used by the freshness-check workflow:
// lastVerified + the URLs below let the scheduled Action detect stale
// or dead-linked entries without a live scraper/backend.
const sourceTracking = {
  lastVerified: z.coerce.date(),
  docsUrl: z.string().url(),
  downloadUrl: z.string().url().optional(),
  repoUrl: z.string().url().optional(),
};

const os = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/os' }),
  schema: z.object({
    name: z.string(),
    tagline: z.string(),
    category: z.enum([
      'general-purpose',
      'wireless',
      'forensics',
      'specialized',
    ]),
    basedOn: z.string(),
    // Optional and hand-judged, not sourced from any upstream taxonomy
    // (none of the 8 tool sources this site syncs from tag anything as
    // "red/blue/purple team" — that's not a concept their own docs
    // use). Left unset for entries that aren't a security-team tool at
    // all (Tails, Whonix, Kodachi, Qubes, Open Secure-K OS — personal
    // privacy/opsec tools; SystemRescue — general sysadmin rescue) so
    // they correctly show under no team filter rather than a guessed
    // one. Classified by the tool/technique's nature (e.g. OSINT recon
    // is a red-team technique per MITRE ATT&CK even where a specific
    // project's mission is investigative, like Trace Labs), not by
    // author intent.
    team: z.enum(['red', 'blue', 'purple']).optional(),
    gettingStarted: z.string(),
    notableTools: z.array(z.string()).default([]),
    // 'auto-synced' distros (Kali, BlackArch, REMnux, Tails) have a
    // scripts/sync-*.mjs pulling their full tools/ collection from an
    // official, structured, per-tool listing; each of those scripts
    // stamps this field itself (see ensureAutoSyncedTag in
    // sync-utils.mjs) at the end of every run, so it self-corrects on
    // the next sync rather than relying on a human to remember it.
    // Defaults to 'manual' (fail closed) so a newly added OS entry is
    // never silently presented as auto-verified when no sync script
    // actually covers it — that only happens when a real sync script
    // claims it. 'manual' means no official structured per-tool
    // listing exists upstream (Parrot has none at all; CAINE's is
    // unstructured prose with no per-tool links; Pentoo's overlay repo
    // mixes real tools with generic Gentoo build plumbing with no
    // authoritative way to tell them apart) — notableTools above is
    // hand-maintained and won't be caught by the freshness-check bot,
    // so the UI flags it for readers to verify independently.
    toolListMaintenance: z.enum(['auto-synced', 'manual']).default('manual'),
    ...sourceTracking,
  }),
});

const tools = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/tools' }),
  // Categories are free-form strings, not an enum: this collection is
  // generated by scripts/sync-kali-tools.mjs from Kali's own category
  // taxonomy (see #categories on each https://www.kali.org/tools/<slug>/
  // page), which this project doesn't control and shouldn't have to
  // keep a hardcoded enum in sync with.
  schema: z.object({
    name: z.string(),
    tagline: z.string(),
    categories: z.array(z.string()).min(1),
    platforms: z.array(z.string()),
    license: z.string().optional(),
    gettingStarted: z.string(),
    commonlyOn: z.array(z.string()).default([]),
    ...sourceTracking,
  }),
});

export const collections = { os, tools };
